# Generated by Django 5.2.3 on 2025-06-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный пакет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Пакет услуг',
                'verbose_name_plural': 'Пакеты услуг',
            },
        ),
    ]
