# Generated by Django 5.2.3 on 2025-06-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='Название клуба')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('opening_hours', models.TextField(verbose_name='Часы работы')),
                ('map_embed_code', models.TextField(help_text='Код для встраивания карты из Google/Yandex Maps', verbose_name='Код карты (iframe)')),
                ('social_facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('social_vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('social_telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('social_instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
