# Generated by Django 5.2.3 on 2025-06-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название платформы')),
                ('icon', models.CharField(help_text='Имя класса иконки (например, "fa-desktop" для Font Awesome)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('duration', models.PositiveIntegerField(choices=[(30, '30 минут'), (60, '1 час'), (120, '2 часа'), (180, '3 часа'), (240, '4 часа'), (300, '5 часов')], verbose_name='Длительность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('platforms', models.ManyToManyField(to='services.platform', verbose_name='Доступные платформы')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('canceled', 'Отменен')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.platform', verbose_name='Платформа')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicepackage', verbose_name='Пакет')),
            ],
        ),
    ]
